// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkmodcwaxxdhkjplnhue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrbW9kY3dheHhkaGtqcGxuaHVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NjAyNjYsImV4cCI6MjA3MTEzNjI2Nn0.gxXUhc6ew36mYTTA047VneBiEO0ckbJ_5jQpCBiZnp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});