// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjktghkheyompsxuwzqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqa3RnaGtoZXlvbXBzeHV3enFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODE4MDMsImV4cCI6MjA2ODE1NzgwM30.GVzkRLgWrL3G7JGqE9hUHB1cH_6et5WOhvDzKA2tc20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});